//! Documentation command - displays formatted command reference

use anyhow::Result;
use colored::Colorize;
use std::process::Command;

pub async fn run() -> Result<()> {
    let docs = generate_docs();

    // Try to use glow for nice terminal rendering
    let glow_available = Command::new("glow")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    if glow_available {
        // Use glow for beautiful markdown rendering
        let mut child = Command::new("glow")
            .arg("-")
            .stdin(std::process::Stdio::piped())
            .spawn()?;

        if let Some(mut stdin) = child.stdin.take() {
            use std::io::Write;
            stdin.write_all(docs.as_bytes())?;
        }

        child.wait()?;
    } else {
        // Fallback: print with basic coloring
        print_docs_fallback(&docs);
    }

    Ok(())
}

fn generate_docs() -> String {
    r#"# Secular CLI - Quick Reference

> **Secular** is a P2P code collaboration tool built on Radicle Heartwood

---

## 🚀 Getting Started

### Initialize a repository
```bash
secular repos init
# Follow the prompts to set name, description, and visibility
```

### Start your node
```bash
secular node start
```

### Check node status
```bash
secular node status
```

---

## 👥 Managing Friends

### Add a friend
```bash
secular friend add --name alice did:key:z6Mk...
```

### List your friends
```bash
secular friend list
secular friend list --detailed  # Show Node IDs
```

### View friend's repositories
```bash
secular friend repos alice
```

### Remove a friend
```bash
secular friend remove alice
```

---

## 📦 Working with Repositories

### Clone a repository
```bash
# Clone from a friend
secular repos clone rad:z4A1... --seed did:key:z6Mk...

# Clone from public seed
secular repos clone rad:z4A1... --seed seed.radicle.xyz:8776
```

### Push changes
```bash
# Push to your Radicle node
secular repos push

# Push to a specific friend
secular repos push --friend alice
```

### Pull changes
```bash
# Pull from Radicle
secular repos pull

# Pull from a specific friend
secular repos pull --friend alice
```

### Sync (pull + push)
```bash
secular repos sync
secular repos sync --friend alice
```

### List repositories
```bash
secular repos list
```

### View repository status
```bash
secular repos status
```

---

## 🌐 Node Management

### Start/Stop/Restart
```bash
secular node start
secular node stop
secular node restart
```

### View connected peers
```bash
secular node peers
```

### Announce your repositories
```bash
# Sync and announce to the network
rad sync --announce

# Or from within a repo
cd /path/to/repo && rad sync --announce
```

### View node storage
```bash
secular node storage
```

### View node logs
```bash
secular node logs
secular node logs --follow  # Follow in real-time
```

---

## 🔒 Security & Scanning

### Scan for secrets
```bash
secular scan /path/to/repo
```

### Run security audit
```bash
secular audit
```

---

## 💡 Tips & Tricks

### Get your Node ID
```bash
rad self --nid
```

### Share your Node ID with friends
Your friends need your Node ID to add you as a remote and clone your repos.

### Troubleshooting connectivity

**If friends can't clone your repos:**

1. Make sure your node is running:
   ```bash
   secular node status
   ```

2. Announce your repository:
   ```bash
   cd /path/to/repo && rad sync --announce
   ```

3. Use a public seed as intermediary:
   ```bash
   rad seed <rid> --seed seed.radicle.xyz:8776
   ```

4. Check if your node port (8776) is forwarded on your router

### Working with multiple repos
You can have multiple repos initialized in different directories. Each one gets its own RID (Repository ID).

---

## 📚 More Help

- Run any command with `--help` for detailed options
- Visit: https://radicle.xyz/docs
- Secular GitHub: https://github.com/joshkornreich/secular

---

Generated by **Secular CLI** - Secure P2P Collaboration
"#.to_string()
}

fn print_docs_fallback(docs: &str) {
    // Simple fallback rendering without glow
    for line in docs.lines() {
        if line.starts_with("# ") {
            println!("\n{}\n", line.trim_start_matches("# ").bright_blue().bold());
        } else if line.starts_with("## ") {
            println!("\n{}", line.trim_start_matches("## ").bright_cyan().bold());
        } else if line.starts_with("### ") {
            println!("\n{}", line.trim_start_matches("### ").cyan());
        } else if line.starts_with("```") {
            // Skip code fence markers in fallback
            continue;
        } else if line.starts_with(">") {
            println!("{}", line.dimmed().italic());
        } else if line.trim() == "---" {
            println!("{}", "─".repeat(60).dimmed());
        } else {
            println!("{}", line);
        }
    }

    println!("\n{}", "💡 Tip: Install 'glow' for better formatting: brew install glow".dimmed());
}
